# Generated by Django 3.0 on 2020-04-09 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20200403_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='數量')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='成立日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='總金額')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='成立日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('active', models.BooleanField(default=True)),
                ('items', models.ManyToManyField(blank=True, to='carts.CartItem')),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
