# Generated by Django 3.0 on 2020-04-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='品名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='價格')),
                ('slug', models.SlugField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='成立日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True, verbose_name='說明')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='產品圖片')),
                ('featured', models.BooleanField(default=False, verbose_name='精選')),
                ('thumbnail', models.BooleanField(default=False, verbose_name='縮圖')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
