# Generated by Django 3.0 on 2020-04-14 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200403_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='產品圖片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='價格')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
