# Generated by Django 3.0 on 2020-04-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200414_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('package', 'package')], default='size', max_length=120),
        ),
    ]
