# Generated by Django 3.0 on 2020-04-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('package', 'package'), ('area', 'area')], default='size', max_length=120),
        ),
    ]
